version: 2
build:
  os: ubuntu-24.04
  tools:
    python: '3.12'
python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
sphinx:
  builder: dirhtml
  fail_on_warning: true
