FROM quay.io/pypa/manylinux2014_aarch64 as build

ENV PLAT=manylinux2014_aarch64
RUN mkdir -p /io/
COPY . /io/
WORKDIR /io/

RUN ./.github/workflows/build-manylinux-wheels.sh

FROM scratch as release
COPY --from=build /io/dist /wheelhouse
